### ISSUE TITLE
Regression in 1.2.0?

### ISSUE THREAD

**Issue by osmestad** [devbridge/js-unused-exports#17]
Hi, 
Thanks for a very interesting tool, but I'm unable to start the latest version (1.2.0), it fails like this:
```
➜  webclient-app git:(develop) ✗ yarn run unused-exports
yarn run v1.19.1
$ yarn run js-unused-exports --config unused-exports-config.json
$ /Users/osmestad/Code/webclient-app/node_modules/.bin/js-unused-exports --config unused-exports-config.json
/Users/osmestad/Code/webclient-app/node_modules/js-unused-exports/bin/js-unused-exports.js:16
execute(program);
^

TypeError: execute is not a function
    at Object.<anonymous> (/Users/osmestad/Code/webclient-app/node_modules/js-unused-exports/bin/js-unused-exports.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
```
The same config works if i downgrade to version 1.1.1, any idea what might be wrong?

**Comment by MaksimEpifanau** [comment]
Have the same issue:
![image](https://user-images.githubusercontent.com/72190678/106274882-05d4d880-6246-11eb-980a-fab4fa4150ca.png)
